apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: single-default-backend-ingress
spec:
  defaultBackend: # providing ingress default backend service
    service:
      name: default-backend
      port:
        number: 80
